import Head from 'next/head';
import AuthGuard from '../guards/AuthGuard';

export default function Home() {
  return (
    <AuthGuard>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main></main>
      </div>
    </AuthGuard>
  );
}
